### ISSUE TITLE
Add better instructions to our common sample projects and scripts

### ISSUE THREAD

**Issue by smithed** [LabVIEW-DCAF/DCAF-Project-Templates#1]
Beazurt commented 27 days ago
The Fixed-Channel Sample Project, Fixed-Channel Script, and Script Module Includes all assume a basic level of understanding from the user. I think we should add better documentation on their Front Panels.

The Fixed-Channel Sample Project should explain the difference between an Input, Output, Parameter, and Result.

The Fixed-Channel Script should explain when it should be run and what it does. It should also explain what the input, process, and output configurations are for (and that they don't need to be used at all unless you renamed something).

The Script Module Includes should explain what it's for, when it should be run, and what the Plugin Search Paths are for.

https://github.com/TBDFramework/TagEditorCore/issues/116

**Comment by smithed** [comment]
apparently I can't assign two people.
@Beazurt @becega one of you should do this since you don't necessarily know what they do, so it should be easier for you to document

**Comment by Beazurt** [comment]
I took a first pass at updating this.  Let me know how it looks.  Do we still need the module includes script in the tools menu?  Seems like we could take it out now that the target node has it.  Waiting to close until this is reviewed.

**Comment by smithed** [comment]
I could see it still being handy if you don't want to load up the whole config editor, but I guess the load time is pretty much the same.

**Comment by Beazurt** [comment]
True.  Ideally a user should run it after making a change in the editor though.  Someone could forget to, but I don't know when their dependencies would change if they didn't do something in the editor first.
