### ISSUE TITLE
Error on trying to remove a channel that doesn't exist

### ISSUE THREAD

**Issue by aggieslaughter** [LabVIEW-DCAF/DCAF-Project-Templates#103]
To reproduce: 

1. Create a new dynamic module. 
2. Load the DCAF standard editor
3. Go to the channel list - the "Remove channel" button is clickable
4. Click the remove channel button - throws an error since there is no check to see if the item to remove is valid

If the channel list is empty on a dynamic module, there is no check for "no valid item selected" when you click the 'remove channel' button - so it throws an error. Should either disable the button if no items is selected, or do a check on removal that there is an item selected before there is an attempt to remove it from the tree.

**Comment by pollockm** [comment]
This may need to also be fixed on existing modules from the dynamic template (scan engine, dds, etc)

**Comment by theSloopJohnB** [comment]
Fixing this issue (which is in review now) will get you from a crazy non-sense error to a sensible one. 
https://github.com/LabVIEW-DCAF/ModuleInterface/issues/32

It should still be fixed though.
