### ISSUE TITLE
Dynamic: Example Test should use the same test config as other tests

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#105]
Other tests generate a test configuration with "Create Test Configuration.vi"

example test.vi uses a hard-coded, different, implementation.  Replace the hard-coded implementation with the common Create Test Configuration to ensure consistency across tests.

**Comment by becega** [comment]
This has been updated. Example test is no longer there was renamed and cleaned as run time test
