### ISSUE TITLE
Static: Runtime Init Test: Check for exec settings hardcoded for processing module

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#110]
In Runtime Initialization Test, we hardcode the test to check that the module does not have any input or output data, only processing. 

This works for the typical case, but we can also have cases where we have input or output channels as well.

(for example, the DAQmx Watchdog module)

**Comment by becega** [comment]
@pollockm Added coment to update the settings with a bookmark. Should this be enough. Also added its Unit test framework test but it is disabled.
