### ISSUE TITLE
Module Templates - Make default to support an OS

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#17]
Currently, the user is asked to define which targets are supported.  By default, the list is empty.  If a user doesn't change the default, the module will not show up in the configuration editor.  This caused me a headache until we figured it out, and seems like an easy trap for a new user (or hands-on attendee) to fall into.

Can we change the default behavior such that all targets are supported by default?  Or at least Windows?

**Comment by becega** [comment]
Yes we should
