### ISSUE TITLE
I/O DCAF Module looks for DCAFConfigurablePluginDecideFeatures

### ISSUE THREAD

**Issue by fmussi** [LabVIEW-DCAF/DCAF-Project-Templates#48]
LV 2016  / DCAF coew \1.0.0.8

When I create a new I/O DCAF module project template, I've this VI search windows popping up:

![image](https://cloud.githubusercontent.com/assets/8535457/20761047/010ab352-b722-11e6-9ea3-8d12f56fc843.png)

It closes after a while so I can properly name and set the location for the plugin, but once I press finish the LV project doesn't open; I have to open it manually: is it expected?

**Comment by becega** [comment]
Its already in the fixed in the next version.
