### ISSUE TITLE
Rename templates to have DCAF as prefix

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#55]
Right now, they're called User Control Module and IO DCAF Module.  I'd like to see a consistent naming convention, perhaps:

DCAF Static Channel Module
DCAF Dynamic Channel Module  ?

Since the user control module can be used to make IO modules, and the IO module can be used to make processing modules, those names seem incorrect to me.

**Comment by becega** [comment]
You want the name change when you select the template> or completely at file level and repo level?

The control Module used to be named Fixed Channel Module but apparently it was confusing. @Beazurt might have more info on this

**Comment by Beazurt** [comment]
I agree the names should be changed for consistency somehow. Static and Dynamic work as long as we give descriptions for which one is easier and what their most common use-cases would be.

I am also OK with just fixing the names in the template creator. It doesn't seem worth it to rename things on disk for right now.

**Comment by becega** [comment]
Runtime Templates name are still missing the DCAF prefix
