### ISSUE TITLE
Close scripted VIs after control project template is instantiated

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#57]
Currently we leave a bunch of scripted VI front panels open.  This looks messy.  Can we close their front panels when scripting is done?

**Comment by becega** [comment]
Leaving the open was done intentionally so they could see what was modified. Closing them shoudl not be an issue. THe original purpose was for the user not having to make it themselves not to be oblivious to it.
