### ISSUE TITLE
Static Module: Tests should pass

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#58]
The tests configured with the control module do not pass.

Serialization test fails with error 538267: A configured channel was not found in the current type definition
Runtime initialization test fails with same error.
Runtime test fails with same error.

Modify channel test looks ok.

**Comment by jwgorman** [comment]
Acceptance Criteria
- Pre scripted unit tests that should pass, pass

**Comment by dbendele** [comment]
Matt appears to have fixed this in previous sweeps through the tests in order to get CI testing working for build

**Comment by pollockm** [comment]
Forgot to close.  Oops.
