### ISSUE TITLE
Static/Dynamic Channel Modules: Create Test Configuration.vi hard-wires channel classifications

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/DCAF-Project-Templates#70]
**Description:**
Supported channel classifications inappropriate for modules using input data and output data. Also, **#MaintenanceRequired** tag should be added to the VI for writing additional configuration parameters (property node items) which need to be tested.

**Fix:** 
	1. Add property node for module "supported classifications" property item.
	2. Wire "supported classifications" to auto-indexing terminal for create new channel.vi.
        3. Add **#MaintenanceRequired** tag, as this code will undoubtedly change for every module.
![image](https://cloud.githubusercontent.com/assets/8442127/23759579/c803c592-04b2-11e7-8f73-c1fbd880f8d5.png)

**Comment by becega** [comment]
This Vi has been updated. This issue no longer applies
