### ISSUE TITLE
Static/Dynamic Channel Modules: Runtime Initialization Test.vi hard-wires channel classifications

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/DCAF-Project-Templates#71]
**Description:**
Test will fail for Static Channel modules that are configured to use input data and output data channels. Boolean result indicator name not sufficiently descriptive, output =  "TRUE" required to pass unit tests, requiring extra configuration step in Unit Test Framework. Annoyance: VI names do not match between templates.

**Fix:** 
	1. Add property node for module "supported classifications" property item.
	2. Conditionally check that expected execution settings match those produced by init.vi.

![image](https://cloud.githubusercontent.com/assets/8442127/23759793/698261f8-04b3-11e7-8e1c-6e69b35519e2.png)

**Comment by becega** [comment]
THis has been removed.
