### ISSUE TITLE
Static/Dynamic Channel Modules: Runtime Test uses default channel data.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/DCAF-Project-Templates#73]
**Description:**
Default data values are used for testing purposes, potentially exposing a DCAF module to potential "False PASS" test results in cases where unsuccessful test might still return the expected (default) output values.

**Fix:** 
	1. Add a Generate Test Data.vi (or similar) in order to generate non-default "dummy" test data for all channels of a test configuration, prior to the execution portion of Runtime Test.vi.

**Comment by becega** [comment]
The test has been updated.
