### ISSUE TITLE
Dynamic Channel Module: Runtime Test example is missing

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/DCAF-Project-Templates#75]
**Description:**
In place of a runtime test appears to be example test.vi, inconsistent with the Static Channel Module template.

**Fix:** 
Replace example test.vi with Runtime Test.vi, well documented as a **#MaintenanceRequired** item, but producing a test "FAIL" result until user modified.

**Comment by becega** [comment]
Added it in https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/pull/119
