### ISSUE TITLE
Static/Dynamic Channel Modules: User defined tests do not facilitate seamless, descriptive Unit Test Framework test creation.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/DCAF-Project-Templates#76]
**Description:**
Boolean result indicator name not sufficiently descriptive, and test Boolean indicators =  "TRUE" are the default "Test PASS" condition. This requires the developer, if creating a UTF test from a VI, to take extra configuration steps in the Unit Test Framework test configuration UI to select the appropriate Boolean indicator output. This extra step could be removed entirely if the "Test PASS" conditions of all user defined test VI's are "FALSE," (and no Error).

**Fix:** 
Improve test VI output indicator names to be more descriptive, and change test pass condition to a "FALSE" boolean output (LED color to red?) for all module test VI's.

**Comment by pollockm** [comment]
...or run the test VI once, then create the unit test with the VI still open.  Will take all current values from VI.  This is the typical workflow for items that need a non-default value as well.
