### ISSUE TITLE
'Write Lines' Data Accessor is Dangerous and Does Not Validate

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Project-Templates#77]
I don't think the Table API should provide access to clobber all lines at once, at least not as part of the template. 'Write Lines' VI is also dangerous in that it does not do any checking for duplicate channel names, invalid data types, etc. In general, Add and Modify line functions should be used instead. If we still think there are valid use-cases for 'Write Lines', it should do a whole lot more internal validation.

**Comment by jwgorman** [comment]
Either: remove the method and update the callers to use the single line implementation, add validation to the multi-line call, or keep it. Talk through with Burt and Benji about which to do.

#78

**Comment by dbendele** [comment]
https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/commit/4e4f12e2e3c620f995cb9d697ade068c51aa0c7c
