### ISSUE TITLE
'Replace Line' Does not check for duplicate channels

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Project-Templates#78]

**Comment by jwgorman** [comment]
Need to add additional validation checking for checking that the user does not have multiple lines with the same names. Modules that use the template will also need to be updated and audited to make they are currently conforming.

In the event the user does use a duplicate name, they will be returned an error

Acceptance Criteria:
- Create issues in other modules that are violating the convention
- Add Checking for duplicate line names
- Return an error if a duplicate name is entered
- Add unit testing to ensure we cannot add duplicate names
