### ISSUE TITLE
Dynamic: Unable to Change Tag Through Configure Channel Dialog

### ISSUE THREAD

**Issue by jacobson3** [LabVIEW-DCAF/DCAF-Project-Templates#79]
Once you create a line, you will not be able to change the tag by clicking the settings button. Error 538351: "tag not found" is thrown from disconnect channels.vi after the configure channels dialog is thrown.

**Comment by jwgorman** [comment]
Acceptance Criteria
- Once you create a tag, you should be able to edit it.
- Check other modules for this behavior if they derived from this template.

**Comment by dbendele** [comment]
@jacobson3, Do you still see this issue?

**Comment by jacobson3** [comment]
@dbendele I do see this error in the published package.

Specifically, this problem occurs when using the settings button to add a tag to a channel which does not have a tag already mapped to it. If this is done, there will be no error visible to the user but one will be generated by Disconnect Channels.vi in Edit Line.vi which will then cause Connect Channel to no-op.

Steps to Reproduce
1. Create new dynamic module from template and add it as a node in the DCAF editor
2. Click the "+" button to create a new line but do not specify a tag.
3. Click the settings cog button and select a tag to map to the channel. Notice how the tag column will not update to the selected tag.

**Comment by dbendele** [comment]
Thanks for providing those Steps to Reproduce! I could have clicked around a lot and still not found that specific usage that exhibits the error.

**Comment by jbellamyNI** [comment]
Looks good!
