### ISSUE TITLE
Add 'Tripple Click To Edit' to User Control Module Parameters Tab

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Project-Templates#8]
People keep trying to double-click and it doesn't work. It'd be nice to find a better way to edit, but for now lets just add more instructions to the UI.

**Comment by smithed** [comment]
its actually "slow double click" but agreed

**Comment by Beazurt** [comment]
I guess I'm impatient.  I just click frantically until it lets me do what I want.

**Comment by smithed** [comment]
multicolumn listbox is like 1995 technology you have to be patient :P

**Comment by becega** [comment]
I think with 2 clicks should eb enough , lets test with the changes we made with the API, if we need something else we will reopen this but in the table API
