### ISSUE TITLE
Update IO Module Template to Use a Recursive To and From String Implementation

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/DCAF-Project-Templates#80]
The shared memory module is a good example of this. I think it is a good best practice that the template should encourage.

**Comment by pollockm** [comment]
It's a good pattern, esp. since it enforces the rule that once something is in configuration, you don't touch it, just change how it is interpreted.

Better to implement as stubbed VI, or to use an OOP decorator pattern?

**Comment by Beazurt** [comment]
Either would work fine, but I think a stubbed VI would work well enough.

**Comment by jwgorman** [comment]
Dynamic template:

Acceptance Criteria
- Implement pattern that happens in shared memory module in this template

**Comment by dbendele** [comment]
committed on local branch; grouping commits to project templates
