### ISSUE TITLE
Add write to Syslog on runtime templates

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Project-Templates#86]
We don't capture top-level errors when trying to launch the engine in Syslog.  Add a write to Syslog on runtime if there was an error launching.

(I.e., eliminate need to see error output terminal on main vi)

**Comment by Beazurt** [comment]
@pollockm isn't that the same as this? https://github.com/LabVIEW-DCAF/StandardEngine/issues/62

**Comment by pollockm** [comment]
Similar.  62 is to have the "engine launched" "engine shutdown" messages.  This is to also capture errors in the process.  Can (and probably should) be squashed into a single issue.

**Comment by theSloopJohnB** [comment]
@Beazurt I think fixed this with lots of logging in the standard engine in [this commit](
https://github.com/LabVIEW-DCAF/StandardEngine/pull/78/commits/0b5f1dc7431d1897de77828c4b20ad858f7ab469)

Can we close this now?
