### ISSUE TITLE
runtime test for Static module needs update and documentation

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/DCAF-Project-Templates#88]
The runtime one is to generic and many test are in individual test they shoudl be removed from here. Also it shoudl have some documentation on what needs to be done with it.

**Comment by theSloopJohnB** [comment]
The idea is that you should be able to run the module without the engine.

There is extra clutter from some of the existing templates. FPGA Module and J1939 modules have good runtime tests to use as an example.
