### ISSUE TITLE
Find Duplicate Vi should not be on the templates

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/DCAF-Project-Templates#95]
This shoudl be higher priority before people switch to the new templates or they will have to do relinking. 
This vi gets linked to the template as it is in the scripts folder. The final code should not reference anything there as it is not in VI lib, and should not have a dependency there. This should be moved to tag editor core, configuration class. 
This might ask for relinking but this file shoudl not be here. 
The file is in : C:\Program Files (x86)\National Instruments\LabVIEW 2014\ProjectTemplates\Source\dcaf configurable plugin module\user control module\scripting\FindDuplicate.vi

but it is used by both the dynamic and static module.  It shoudl be part of TBM configuration on the https://github.com/LabVIEW-DCAF/ModuleInterface/

**Comment by dbendele** [comment]
this was addressed in commits:
3ff11a7d1eedea22bb5fffcccbb2fb4d9efd552d
235e1894d3fbf9b9a3efd76075465175a690b94d

https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/commit/ab881194b69a1a1be026641acd7f9b010c3c725f
