### ISSUE TITLE
Reduce File path of the templates. 

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/DCAF-Project-Templates#96]
The file path for the templates is to long. 
C:\Program Files (x86)\National Instruments\LabVIEW 2017\ProjectTemplates\Source\dcaf configurable plugin module\user control module
C:\Program Files (x86)\National Instruments\LabVIEW 2017\ProjectTemplates\Source\dcaf configurable plugin module\io plugin

We can probably shorter them to DCAF Plugin Module\Static and DCAF Plugin Module\Dynamic, it will make them be similar to the actual name they have on the templates.  Also will prevent some issues with the build server in which paths are to long.  This should not affect existing modules once issue #95 is fixed as is the only VI that appears on dependencies from this directories. 

This should be done before people start using the new templates.

**Comment by dbendele** [comment]
Ben's change:
https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/pull/98
